[package]
name = "myvo-coin"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.2"
ed25519-dalek = { version = "1", features = ["serde"] }
rand = "0.7"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"